cd %~d0
cd %DEMOS_PATH%

md %DEMOS_PATH%\RELAPSE\DATABIN\CASCADE
md %DEMOS_PATH%\RELAPSE\DATABIN\EGYPTIA
md %DEMOS_PATH%\RELAPSE\DATABIN\END
md %DEMOS_PATH%\RELAPSE\DATABIN\GRAFIK_S
md %DEMOS_PATH%\RELAPSE\DATABIN\INFO
md %DEMOS_PATH%\RELAPSE\DATABIN\LIQUID
md %DEMOS_PATH%\RELAPSE\DATABIN\SHADE
md %DEMOS_PATH%\RELAPSE\DATABIN\SLIDE
md %DEMOS_PATH%\RELAPSE\DATABIN\ZIKS

%DEMOS_PATH%\BIN\EXTERN\wmake %ALL% /f %DEMOS_PATH%\RELAPSE\TOOLS\BATCH\relapse.mak 
  
%DEMOS_PATH%\BIN\TOOLS\Imager.exe %DEMOS_PATH%\RELAPSE\RELAPSE1.INI %DEMOS_PATH%\
%DEMOS_PATH%\BIN\TOOLS\Imager.exe %DEMOS_PATH%\RELAPSE\RELAPSE2.INI %DEMOS_PATH%\

type %DEMOS_PATH%\RELAPSE\RELAPSE1.TXT
type %DEMOS_PATH%\RELAPSE\RELAPSE2.TXT
