#ifndef DEMOS_INVERT_DRIVE
#   define DEMOS_INVERT_DRIVE 1
#endif
#include "D:\PROJECTS\DEMOS\SCREENS\SNDTRACK.C"

#include "D:\PROJECTS\DEMOS\DEMOS.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\ALLOC.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\BITMAP.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\COLORS.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\SOUND.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\FSM.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\LOAD.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\RASTERS.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\STANDARD.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\SYSTEM.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\TRACE.C"

#include "D:\PROJECTS\DEMOS\DISK1.C"
#include "D:\PROJECTS\DEMOS\DISK2.C"

#include "D:\PROJECTS\DEMOS\SCREENS\SCREENS.C"
#include "D:\PROJECTS\DEMOS\SCREENS\POLYZOOM.C"
#include "D:\PROJECTS\DEMOS\SCREENS\VISUALIZ.C"
#include "D:\PROJECTS\DEMOS\SCREENS\SLIDES.C"
#include "D:\PROJECTS\DEMOS\SCREENS\FUGIT.C"
#include "D:\PROJECTS\DEMOS\SCREENS\INTERLUD.C"
#include "D:\PROJECTS\DEMOS\SCREENS\MORPH.C"
