		* Courbe	12

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	300*10	* Longueur de file * 10
		dc.w	48*8*1	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	2	* Pas de la lissajou en x
		dc.w	2	*		 	y
	 	dc.w	75	* Rayon horizontal lissajou
	 	dc.w	75	* Rayon vertical lissajou
		dc.w	0	* Angle de depart * 2 en x
	 	dc.w	0	* 	

		* Courbe	11

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	70*10	* Longueur de file * 10
		dc.w	48*8*4	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	4	* Pas de la lissajou en x
		dc.w	2	*		 	y
	 	dc.w	80	* Rayon horizontal lissajou
	 	dc.w	75	* Rayon vertical lissajou
		dc.w	200	* Angle de depart * 2 en x
	 	dc.w	50	* 		

		* Courbe	13

		dc.w	0	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	1	*			icx
		dc.w	2	*			icy
		dc.w	50*10	* Longueur de file * 10
		dc.w	48*8*8	* Increment rotation * 48*8
		dc.w	160	* Centre de la lissajou	 x
		dc.w	100	* 			 y
		dc.w	6	* Pas de la lissajou en x
		dc.w	2	*		 	y
	 	dc.w	100	* Rayon horizontal lissajou
	 	dc.w	50	* Rayon vertical lissajou
		dc.w	20	* Angle de depart * 2 en x
	 	dc.w	0	* 			 y

		* Courbe	9

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	70*10	* Longueur de file * 10
		dc.w	48*8*4	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	8	* Pas de la lissajou en x
		dc.w	2	*		 	y
	 	dc.w	135	* Rayon horizontal lissajou
	 	dc.w	75	* Rayon vertical lissajou
		dc.w	700	* Angle de depart * 2 en x
	 	dc.w	50	* 			

		* Courbe	8

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	50*10	* Longueur de file * 10
		dc.w	48*8*8	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	6	* Pas de la lissajou en x
		dc.w	4	*		 	y
	 	dc.w	100	* Rayon horizontal lissajou
	 	dc.w	50	* Rayon vertical lissajou
		dc.w	400	* Angle de depart * 2 en x
	 	dc.w	0	* 			

		* Courbe	7

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	150*10	* Longueur de file * 10
		dc.w	48*8*8	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	2	* Pas de la lissajou en x
		dc.w	6	*		 	y
	 	dc.w	100	* Rayon horizontal lissajou
	 	dc.w	50	* Rayon vertical lissajou
		dc.w	20	* Angle de depart * 2 en x
	 	dc.w	0	* 			 y

		* Courbe	1

		dc.w	0	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	3	*			icx
		dc.w	2	*			icy
		dc.w	60*10	* Longueur de file * 10
		dc.w	48*8*2	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	8	* Pas de la lissajou en x
		dc.w	6	*	  	 	y
	 	dc.w	10	* Rayon horizontal lissajou
	 	dc.w	50	* Rayon vertical lissajou
		dc.w	50	* Angle de depart * 2 en x
	 	dc.w	700	* 			 

		* Courbe	2

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	0	* Position de depart:	x
		dc.w	0	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	30*10	* Longueur de file * 10
		dc.w	48*8*2	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	8	* Pas de la lissajou en x
		dc.w	6	*	  	 	y
	 	dc.w	135	* Rayon horizontal lissajou
	 	dc.w	75	* Rayon vertical lissajou
		dc.w	50	* Angle de depart * 2 en x
	 	dc.w	700	* 			 y
		
		* Courbe	3

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	0	* Position de depart:	x
		dc.w	0	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	300*10	* Longueur de file * 10
		dc.w	48*8*4	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	2	* Pas de la lissajou en x
		dc.w	2	*	  	 	y
	 	dc.w	135	* Rayon horizontal lissajou
	 	dc.w	75	* Rayon vertical lissajou
		dc.w	100	* Angle de depart * 2 en x
	 	dc.w	0	* 			 y

		* Courbe 	10

		dc.w	0	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	1	*			icx
		dc.w	1	*			icy
		dc.w	80*10	* Longueur de file * 10
		dc.w	48*8*2	* Increment rotation * 48*8
		dc.w	160	* Centre de la lissajou	 x
		dc.w	100	* 			 y
		dc.w	6	* Pas de la lissajou en x
		dc.w	2	*		 	y
	 	dc.w	100	* Rayon horizontal lissajou
	 	dc.w	50	* Rayon vertical lissajou
		dc.w	20	* Angle de depart * 2 en x
	 	dc.w	0	* 			 y

		* Courbe	4

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	0	* Position de depart:	x
		dc.w	0	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	300*10	* Longueur de file * 10
		dc.w	48*8*1	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	6	* Pas de la lissajou en x
		dc.w	2	*	  	 	y
	 	dc.w	135	* Rayon horizontal lissajou
	 	dc.w	75	* Rayon vertical lissajou
		dc.w	20	* Angle de depart * 2 en x
	 	dc.w	0	* 			 y

		* Courbe	5

		dc.w	1	* Curve: 0=rebondissant / 1=lissajou
		dc.w	0	* Position de depart:	x
		dc.w	0	* 			y
		dc.w	1	*			icx
		dc.w	1	*			icy
		dc.w	200*10	* Longueur de file * 10
		dc.w	48*8*2	* Increment rotation * 48*8
		dc.w	136	* Centre de la lissajou	 x
		dc.w	76	* 			 y
		dc.w	2	* Pas de la lissajou en x
		dc.w	2	*		 	y
	 	dc.w	136	* Rayon horizontal lissajou
	 	dc.w	75	* Rayon vertical lissajou
		dc.w	0	* Angle de depart * 2 en x
	 	dc.w	0	* 			 y

		* Courbe	6

		dc.w	0	* Curve: 0=rebondissant / 1=lissajou
		dc.w	160	* Position de depart:	x
		dc.w	100	* 			y
		dc.w	2	*			icx
		dc.w	1	*			icy
		dc.w	50*10	* Longueur de file * 10
		dc.w	48*8*1	* Increment rotation * 48*8
		dc.w	160	* Centre de la lissajou	 x
		dc.w	100	* 			 y
		dc.w	6	* Pas de la lissajou en x
		dc.w	2	*		 	y
	 	dc.w	100	* Rayon horizontal lissajou
	 	dc.w	50	* Rayon vertical lissajou
		dc.w	20	* Angle de depart * 2 en x
	 	dc.w	0	* 			 y



