#ifndef DEMOS_INVERT_DRIVE
#   define DEMOS_INVERT_DRIVE 1
#endif
#include "RELAPSE\SRC\DEMOS.C"

#include "DEMOSDK\ALLOC.C"
#include "DEMOSDK\BITMAP.C"
#include "DEMOSDK\COLORS.C"
#include "DEMOSDK\FSM.C"
#include "DEMOSDK\LOAD.C"
#include "DEMOSDK\RASTERS.C"
#include "DEMOSDK\STANDARD.C"
#include "DEMOSDK\SYSTEM.C"
#include "DEMOSDK\TRACE.C"
#include "DEMOSDK\MODX2MOD.C"
#include "DEMOSDK\DATA\DATA.C"

#include "FX\COLPLANE\COLPLANE.C"
#include "FX\MOD\MOD.C"

#include "RELAPSE\RELAPSE1.C"
#include "RELAPSE\RELAPSE2.C"

#include "RELAPSE\SRC\SCREENS.C"
#include "RELAPSE\SRC\LOADER\PRELOAD.C"
#include "RELAPSE\SRC\SPLASH\SPLASH.C"
#include "RELAPSE\SRC\INTRO\INTRO.C"
#include "RELAPSE\SRC\LIQUID\LIQUID.C"
#include "RELAPSE\SRC\EGYPTIA\EGYPTIA.C"
#include "RELAPSE\SRC\GRAFIK_S\GRAFIK_S.C"
#include "RELAPSE\SRC\INTERLUD\INTERLUD.C"
#include "RELAPSE\SRC\CASCADE\CASCADE.C"
#include "RELAPSE\SRC\SHADE\SHADE.C"
#include "RELAPSE\SRC\SPACEF\SPACEF.C"
#include "RELAPSE\SRC\END\END.C"
#include "RELAPSE\SRC\INFO\INFO.C"
#include "RELAPSE\SRC\LOADER\LOADER.C"
#include "RELAPSE\SRC\FASTMENU\FASTMENU.C"
