#ifndef DEMOS_INVERT_DRIVE
#   define DEMOS_INVERT_DRIVE 1
#endif

#include "D:\PROJECTS\DEMOS\REBIRTH\DISK1.H"
#include "D:\PROJECTS\DEMOS\REBIRTH\DISK2.H"

#include "D:\PROJECTS\DEMOS\SYNSOUND\SRC\DEMOS.C"

#include "D:\PROJECTS\DEMOS\DEMOSDK\ALLOC.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\BITMAP.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\COLORS.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\FSM.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\LOAD.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\RASTERS.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\STANDARD.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\SYNTH.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\SYSTEM.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\TRACE.C"

#include "D:\PROJECTS\DEMOS\SYNSOUND\SRC\SCREENS.C"
#include "D:\PROJECTS\DEMOS\SYNSOUND\SRC\PLAYER.C"
