#ifndef DEMOS_INVERT_DRIVE
#   define DEMOS_INVERT_DRIVE 1
#endif

#define DEMOS_LOAD_FROMHD

#include "SYNSOUND\SRC\DEMOS.C"

#include "DEMOSDK\ALLOC.C"
#include "DEMOSDK\BITMAP.C"
#include "DEMOSDK\COLORS.C"
#include "DEMOSDK\FSM.C"
#include "DEMOSDK\LOAD.C"
#include "DEMOSDK\RASTERS.C"
#include "DEMOSDK\STANDARD.C"
#include "DEMOSDK\SYSTEM.C"
#include "DEMOSDK\TRACE.C"
#include "DEMOSDK\DATA\DATA.C"

#include "SYNSOUND\SRC\SYNTH.C"
#include "SYNSOUND\SRC\SCREENS.C"
#include "SYNSOUND\SRC\PLAYER.C"
