#ifndef DEMOS_INVERT_DRIVE
#   define DEMOS_INVERT_DRIVE 1
#endif
#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\SNDTRACK.C"
#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\DEMOS.C"

#include "D:\PROJECTS\DEMOS\DEMOSDK\ALLOC.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\BITMAP.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\COLORS.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\SOUND.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\FSM.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\LOAD.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\RASTERS.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\STANDARD.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\SYSTEM.C"
#include "D:\PROJECTS\DEMOS\DEMOSDK\TRACE.C"

#include "D:\PROJECTS\DEMOS\REBIRTH\DISK1.C"
#include "D:\PROJECTS\DEMOS\REBIRTH\DISK2.C"

#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\SCREENS.C"
#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\POLYZOOM.C"
#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\VISUALIZ.C"
#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\SLIDES.C"
#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\FUGIT.C"
#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\INTERLUD.C"
#include "D:\PROJECTS\DEMOS\REBIRTH\SRC\MORPH.C"
