#ifndef DEMOS_INVERT_DRIVE
#   define DEMOS_INVERT_DRIVE 1
#endif
#include "REBIRTH\SRC\SNDTRACK.C"
#include "REBIRTH\SRC\DEMOS.C"

#include "DEMOSDK\ALLOC.C"
#include "DEMOSDK\BITMAP.C"
#include "DEMOSDK\COLORS.C"
#include "DEMOSDK\SOUND.C"
#include "DEMOSDK\FSM.C"
#include "DEMOSDK\LOAD.C"
#include "DEMOSDK\RASTERS.C"
#include "DEMOSDK\STANDARD.C"
#include "DEMOSDK\SYSTEM.C"
#include "DEMOSDK\TRACE.C"

#include "DEMOSDK\DATA\DATA.C"

#include "REBIRTH\DISK1.C"
#include "REBIRTH\DISK2.C"

#include "REBIRTH\SRC\SCREENS.C"
#include "REBIRTH\SRC\POLYZOOM.C"
#include "REBIRTH\SRC\VISUALIZ.C"
#include "REBIRTH\SRC\SLIDES.C"
#include "REBIRTH\SRC\FUGIT.C"
#include "REBIRTH\SRC\INTERLUD.C"
#include "REBIRTH\SRC\MORPH.C"
