call PC\BlsConvert.bat

SET BLSPLAY=PC\Debug\BLSplay_debug.exe
SET TEXTDIFF="C:\Program Files (x86)\WinMerge\WinMergeU.exe"

%BLSPLAY% %BLSFOLDER%\DATA\QUICKIE.BLS  -test
%BLSPLAY% %BLSFOLDER%\DATA\_QUICKIE.BLS -test
%BLSPLAY% %BLSFOLDER%\DATA\QUICKIEX.BLS -test
%BLSPLAY% %BLSFOLDER%\DATA\LOADER.BLS   -test
%BLSPLAY% %BLSFOLDER%\DATA\NUTEK3.BLS   -test

%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\ARPEGGIO.BLS -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\BALANCE.BLS  -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\CLIENT.BLS   -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\DELAY.BLS    -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\EXTENDED.BLS -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\FINETUNE.BLS -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\JUMPS.BLS    -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\LONGLOOP.BLS -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\MASK.BLS     -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\PATRLOOP.BLS -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\SAMPLE.BLS   -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\SPEED.BLS    -test
%BLSPLAY% %BLSFOLDER%\DATA\UNITTEST\VOLUME.BLS   -test

%TEXTDIFF% /f *.RAW;*.TXT /maximize /x U:\HDisk\STE_D\PROJECTS\DEMOS\_logs\PC\ %BLSFOLDER%\AUTOTEST\PC\

exit
