#ifndef DEMOS_INVERT_DRIVE
#   define DEMOS_INVERT_DRIVE 1
#endif

#include "BLITZIK\SRC\DEMOS.C"

#include "DEMOSDK\SYSTEM.C"
#include "DEMOSDK\DATA\DATA.C"
#include "DEMOSDK\ALLOC.C"
#include "DEMOSDK\BLSZIO.C"
#include "DEMOSDK\BLSZPLAY.C"
#include "DEMOSDK\CODEGEN.C"
#include "DEMOSDK\COLORS.C"
#include "DEMOSDK\FSM.C"
#include "DEMOSDK\LOAD.C"
#include "DEMOSDK\RASTERS.C"
#include "DEMOSDK\STANDARD.C"
#include "DEMOSDK\SYNTHYMD.C"
#include "DEMOSDK\TRACE.C"

#include "FX\VECTOR\VECTOR.C"
#include "FX\COLPLANE\COLPLANE.C"
#include "FX\VREGANIM\VREGANIM.C"
#include "FX\SNDSHADE\SNDSHADE.C"
#include "FX\STARFILD\STARFILD.C"
#include "FX\TEXT\TEXT.C"
#include "FX\SMPLCURV\SMPLCURV.C"

#include "BLITZIK\BLITZWAV.C"

#include "BLITZIK\SRC\SCREENS.C"
#include "BLITZIK\SRC\INTRO\INTRO.C"
#include "BLITZIK\SRC\SSHADE\SSHADE.C"
#include "BLITZIK\SRC\SAMCURVE\SAMCURVE.C"
#include "BLITZIK\SRC\SAMSCROL\SAMSCROL.C"
#include "BLITZIK\SRC\SPACEWAV\SPACEWAV.C"
#include "BLITZIK\SRC\WAVHERO\WAVHERO.C"
#include "BLITZIK\SRC\ALLCURVE\ALLCURVE.C"
#include "BLITZIK\SRC\LAYERZ\LAYERZ.C"
#include "BLITZIK\SRC\LOADER\LOADER.C"
#include "BLITZIK\SRC\MENU\MENU.C"
#include "BLITZIK\SRC\INFO\INFO.C"

#include "DEMOSDK\UNITTEST.C"
