#define DEMOS_LOAD_FROMHD

#include "SYNTHYM\SRC\DEMOS.C"

#include "DEMOSDK\ALLOC.C"
#include "DEMOSDK\BITMAP.C"
#include "DEMOSDK\COLORS.C"
#include "DEMOSDK\LOAD.C"
#include "DEMOSDK\RASTERS.C"
#include "DEMOSDK\STANDARD.C"
#include "DEMOSDK\SYNTHYM.C"
#include "DEMOSDK\SYNTHYMD.C"
#include "DEMOSDK\YMDISP.C"
#include "DEMOSDK\SYSTEM.C"
#include "DEMOSDK\TRACE.C"
#include "DEMOSDK\DATA\DATA.C"

#include "SYNTHYM\SRC\PLAYER.C"
